### Post
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "yuyu"
}

### Delete
DELETE http://localhost:3000/playlists
Content-Type: application/json

{
  "id": "1"
}


### Update
PATCH http://localhost:3000/playlists
Content-Type: application/json

{
  "id": "2",
  "name": "jj"
}