### Add song
PUT http://localhost:3000/10/songs
Content-Type: application/json

{
  "songId": 1,
  "votesNb": 8
}
### Delete
DELETE http://localhost:3000/playlist
Content-Type: application/json

{
  "songId": 1,
  "playlistId": 3
}

### Get
GET http://localhost:3000/playlist
Content-Type: application/json

{
  "songId": 1,
  "playlistId": 2
}

### Update submitter
PATCH http://localhost:3000/playlist
Content-Type: application/json

{
  "songId": 1,
  "playlistId": 2,
  "submitter_id": 4
}

### Update votesNb
PATCH http://localhost:3000/playlist
Content-Type: application/json

{
  "songId": 1,
  "playlistId": 3,
  "votesNb": 15
}

