### Add playlist
PUT http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "testPlaylist"
}

### Add playlist
PUT http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "toRemove"
}

### Delete
DELETE http://localhost:3000/playlists
Content-Type: application/json

{
  "id": "2"
}

### Add playlist
PUT http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "toUpdate"
}


### Update
PATCH http://localhost:3000/playlists
Content-Type: application/json

{
  "id": "2",
  "name": "Updated"
}