### Add song 1
PUT http://localhost:3000/songs
Content-Type: application/json

{
  "name": "titi",
  "album": "banger",
  "artist": "stikmou",
  "thumbnail": "url_album"
}

### Add song 2
PUT http://localhost:3000/songs
Content-Type: application/json

{
  "name": "castor",
  "album": "anger",
  "artist": "chevalito",
  "thumbnail": "url_album"
}

### Add song 3
PUT http://localhost:3000/songs
Content-Type: application/json

{
  "name": "This is were I belong to",
  "album": "gondole",
  "artist": "eddy-malou",
  "thumbnail": "url_album"
}

### Add song 4
PUT http://localhost:3000/songs
Content-Type: application/json

{
  "name": "The longest name of a song ever",
  "album": "anger",
  "artist": "chevalito",
  "thumbnail": "url_album"
}

### Add song 5
PUT http://localhost:3000/songs
Content-Type: application/json

{
  "name": "I had something flooding my veins",
  "album": "banger",
  "artist": "stikmou",
  "thumbnail": "url_album"
}


### Delete song
DELETE http://localhost:3000/songs
Content-Type: application/json

{
  "id": 9
}

### Search song
POST http://localhost:3000/songs
Content-Type: application/json

{
  "name": "A Blessing and A Curse",
  "artist": "Atomica Music"
}