### Add song
PUT http://localhost:3000/songs
Content-Type: application/json

{
  "name": "titi",
  "album": "banger",
  "artist": "stikmou",
  "thumbnail": "url_album"
}

### Add song
PUT http://localhost:3000/songs
Content-Type: application/json

{
  "name": "castor",
  "album": "anger",
  "artist": "chevalito",
  "thumbnail": "url_album"
}

### Delete song
DELETE http://localhost:3000/songs
Content-Type: application/json

{
  "id": 2
}

### Get song
GET http://localhost:3000/songs
Content-Type: application/json

{
  "id": "1"
}