### Post
POST http://localhost:3000/votes
Content-Type: application/json

{
  "userId": 1,
  "playlistId": 2,
  "songId": 3
}

### Delete
DELETE http://localhost:3000/votes
Content-Type: application/json

{
  "userId": 1,
  "playlistId": 2,
  "songId": 3
}


### Update
PATCH http://localhost:3000/votes
Content-Type: application/json

{
  "id": "2",
  "name": "jj"
}